services:
  - type: web
    name: coinbase-clone-api
    env: node
    region: ohio
    plan: free
    buildCommand: cd backend && npm install && npm run seed
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URI
        scope: build,runtime
      - key: CORS_ORIGIN
        value: https://musharafa-crypto-app.netlify.app
        scope: build,runtime
